### ISSUE TITLE
Data mapping for KB data

### ISSUE THREAD

**Issue by larsmans** [beeldengeluid/AVResearcherXL#5]
@IsaacHaze tells me you might have a data mapping for the KB data. Is that true, and can you commit it? I'm having trouble getting AVRXL to run; I might have my data in a different format than you guys do.

**Comment by justinvw** [comment]
I'd first like to properly document the index settings and mappings we currently use within AVResearcherXL before committing them. In the meantime I've created a gist with an example doc, the index settings and the mapping of the KB index: https://gist.github.com/justinvw/1f865cf7a84e175472fe. This should hopefully get you started. There are also some relevant settings in `settings.py` under `COLLECTIONS_CONFIG`.

**Comment by larsmans** [comment]
Cool, that's a great help.

**Comment by larsmans** [comment]
Any news on this? I understand you want to push complete and correct docs, but even shreds of correct docs would help me get further.
